[package]
name          = "smartcols-sys"
description   = "Unsafe Rust bindings for libsmartcols"
version       = "0.1.4" # Remember to update version in `html_root_url`.
authors       = ["Koutheir Attouchi <koutheir.attouchi@microdoc.com>"]
edition       = "2024"
rust-version  = "1.88"
readme        = "README.md"
license       = "MIT"
keywords      = ["ffi", "bindings", "table", "column", "formatting"]
build         = "build.rs"
links         = "smartcols"
documentation = "https://docs.rs/smartcols-sys"
homepage      = "https://github.com/microdoc/smartcols-sys.git"
repository    = "https://github.com/microdoc/smartcols-sys.git"

categories = [
    "external-ffi-bindings",
    "os::linux-apis",
    "text-processing",
    "value-formatting",
]

# https://rust-lang.github.io/api-guidelines/checklist.html
#
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
#restriction = { level = "warn", priority = -1 }
all      = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[build-dependencies]
bindgen = { version = "0.72" }
walkdir = { version = "2" }
dunce   = { version = "1" }
cc      = { version = "1" }

[features]
static = []

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
# Supported target are all user-land Linux platforms.
#
# Building on musl-based systems requires:
# ```
# env RUSTFLAGS=-Ctarget-feature=-crt-static cargo test
# ```
targets = [
    "aarch64-linux-android",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu_ilp32",
    "aarch64-unknown-linux-musl",
    "aarch64_be-unknown-linux-gnu",
    "aarch64_be-unknown-linux-gnu_ilp32",
    "arm-linux-androideabi",
    "arm-unknown-linux-gnueabi",
    "arm-unknown-linux-gnueabihf",
    "arm-unknown-linux-musleabi",
    "arm-unknown-linux-musleabihf",
    "armv4t-unknown-linux-gnueabi",
    "armv5te-unknown-linux-gnueabi",
    "armv5te-unknown-linux-musleabi",
    "armv5te-unknown-linux-uclibceabi",
    "armv7-linux-androideabi",
    "armv7-unknown-linux-gnueabi",
    "armv7-unknown-linux-gnueabihf",
    "armv7-unknown-linux-musleabi",
    "armv7-unknown-linux-musleabihf",
    "hexagon-unknown-linux-musl",
    "i586-unknown-linux-gnu",
    "i586-unknown-linux-musl",
    "i686-linux-android",
    "i686-unknown-linux-gnu",
    "i686-unknown-linux-musl",
    "mips-unknown-linux-gnu",
    "mips-unknown-linux-musl",
    "mips-unknown-linux-uclibc",
    "mips64-unknown-linux-gnuabi64",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-gnuabi64",
    "mips64el-unknown-linux-muslabi64",
    "mipsel-unknown-linux-gnu",
    "mipsel-unknown-linux-musl",
    "mipsel-unknown-linux-uclibc",
    "mipsisa32r6-unknown-linux-gnu",
    "mipsisa32r6el-unknown-linux-gnu",
    "mipsisa64r6-unknown-linux-gnuabi64",
    "mipsisa64r6el-unknown-linux-gnuabi64",
    "powerpc-unknown-linux-gnu",
    "powerpc-unknown-linux-gnuspe",
    "powerpc-unknown-linux-musl",
    "powerpc64-unknown-linux-gnu",
    "powerpc64-unknown-linux-musl",
    "powerpc64le-unknown-linux-gnu",
    "powerpc64le-unknown-linux-musl",
    "riscv32gc-unknown-linux-gnu",
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "sparc-unknown-linux-gnu",
    "sparc64-unknown-linux-gnu",
    "thumbv7neon-linux-androideabi",
    "thumbv7neon-unknown-linux-gnueabihf",
    "thumbv7neon-unknown-linux-musleabihf",
    "x86_64-linux-android",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnux32",
    "x86_64-unknown-linux-musl",
]
